name: CI
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    types: [opened]
    paths-ignore:
      - 'README.md'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest   
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v3
      - name: Clone redis tester
        uses: actions/checkout@v4
        with:
          repository: hhow09/redis-tester
          token: ${{ secrets.TESTER_REPO_PAT }}
          path: redis-tester
      - name: build
        run: |
          go build -o redis-server app/*.go
      - name: Run redis tester
        run: |
          current_dir=$(pwd)
          cd redis-tester
          echo "CODECRAFTERS_SUBMISSION_DIR="$current_dir" \n" >> .env
          echo "EXEC_FROM=$(pwd)" >> .env
          cat .env
          make test_all_with_redis