name: CI
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    types: [opened]
    paths-ignore:
      - 'README.md'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest   
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run tests
        run: go test ./... -v -p 1